name = "TopSingleLayer"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TopSingleLayer"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0"

[[require]]
name = "VCVio"
git = "https://github.com/Verified-zkEVM/VCV-io.git"
rev = "v4.22.0"

[[lean_lib]]
name = "TopSingleLayer"
leanOptions = { warn.sorry = true, warningAsError = false, linter.unusedVariables = false }
